data:
  train_path: ./data/train_expanded.csv
  dev_path: ./data/dev_expanded.csv
  val_path: ./data/dev.csv
  predict_path: ./data/test.csv
  submission_path: ./data/sample_submission.csv
  output_path: ./output/
  checkpoint_path: ./checkpoint/
model:
  model_name: team-lucid/deberta-v3-base-korean
train:
  batch_size: 16
  learning_rate: 1e-5
  max_epoch: 10
  shuffle: true
