model:
    model_name: 'snunlp/KR-ELECTRA-discriminator'
    
train:
    batch_size: 16
    max_epochs: 10
    shuffle: True
    learning_rate: 1e-5

data:
    train_path: './data/train.csv'
    dev_path: './data/dev.csv'
    test_path: './data/dev.csv'
    predict_path: './data/test.csv'
    submission_path: './data/sample_submission.csv'
    output_path: './output/'
